spring:
  application:
    name: movement_stock
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: stock_user
    password: stock_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
